# Autogenerated from /root/tc-build/llvm-project/lld/test/lit.site.cfg.py.in
# Do not edit!

# Allow generated file to be relocatable.
def path(p):
    if not p: return ''
    return os.path.join(os.path.dirname(os.path.abspath(__file__)), p)


import lit.util

config.have_dia_sdk = lit.util.pythonize_bool("0")
config.llvm_src_root = "/root/tc-build/llvm-project/llvm"
config.llvm_obj_root = "/root/tc-build/build/llvm/stage1"
config.llvm_tools_dir = "/root/tc-build/build/llvm/stage1/./bin"
config.llvm_libs_dir = "/root/tc-build/build/llvm/stage1/./lib"
config.llvm_libxml2_enabled = 0
config.lit_tools_dir = ""
config.lld_obj_root = "/root/tc-build/build/llvm/stage1/tools/lld"
config.lld_libs_dir = "/root/tc-build/build/llvm/stage1/./lib"
config.lld_tools_dir = "/root/tc-build/build/llvm/stage1/./bin"
config.target_triple = "x86_64-unknown-linux-gnu"
config.python_executable = "/usr/bin/python3.8"
config.have_zlib = 1
config.sizeof_void_p = 8

# Support substitution of the tools and libs dirs with user parameters. This is
# used when we can't determine the tool dir at configuration time.
try:
    config.llvm_tools_dir = config.llvm_tools_dir % lit_config.params
    config.llvm_libs_dir = config.llvm_libs_dir % lit_config.params
except KeyError as e:
    key, = e.args
    lit_config.fatal("unable to find %r parameter, use '--param=%s=VALUE'" % (key,key))

import lit.llvm
lit.llvm.initialize(lit_config, config)

# Let the main config do the real work.
lit_config.load_config(config, "/root/tc-build/llvm-project/lld/test/lit.cfg.py")
